### ISSUE TITLE
De-duplication: final vs progressive

### ISSUE THREAD

**Issue by robpalme** [fabiospampinato/tiny-readdir-glob#1]
https://github.com/fabiospampinato/tiny-readdir-glob/blob/40e2d697635365e350f39006874e19f599479c47/src/index.ts#L55

The loop accumulates into an array and does a one-time de-deduplication at the end via Set creation.

I'm curious.  Do you know how the performance compares to progressively accumulating into a Set?

**Comment by fabiospampinato** [comment]
I haven't checked 🤔. I'd guess doing it this way when searching into one folder only is probably a bit faster, because `uniqFlat` doesn't actually do anything in that scenario. 

If those arrays actually need to get merged though it seems unclear. It may be better to delete these arrays completely, telling `tiny-readdir` to give us each value via a callback instead, and putting that straight into the set for deduplication.

Although if we are searching into folders that are not one inside the other, like `/foo` and `/bar`, and we are not following symlinks or just no symlinks have been found, I think we would actually need no deduplication and just concatenating the arrays would be best. This part of the library is not particularly optimized, I haven't found it to be a problem yet.
